### ISSUE TITLE
Add MedTagger images to the Docker Hub

### ISSUE THREAD

**Issue by jpowie01** [medtagger/MedTagger#336]
## Current Behavior

Docker Images has to be built each time before setting up a MedTagger instance.

## Expected Behavior

Administrator should be able to pull MedTagger images from global Docker Hub. Then, he/she should be able to pull them like this:

```bash
$> docker pull medtagger/rest
$> docker pull medtagger/websocket
$> ...
```

## Tasks to do

- [ ] Prepare Makefile with entries to automate Docker Build and Push.
- [ ] Publish Docker Images to the Docker Hub.
- [ ] Check if everything can be pulled and set up properly.

## Additional comment

Docker Images should also be versioned in the same way we version code/platform:

```bash
$> docker pull medtagger/rest:1.2.3
```

This Issue bases on a POC (#315).
