### ISSUE TITLE
Upgrade Celery to the latest version

### ISSUE THREAD

**Issue by jpowie01** [medtagger/MedTagger#449]
## Current Behavior

Celery was downgraded to <4.2.0 due to unstable Scans Upload in #447.

## Expected Behavior

We should bring new version of Celery as soon as their maintainers fix this bug.

## Tasks to do

- [ ] Prepare easy reproduction of this Issue
- [ ] Submit a bug/issue with above reproduction to Celery maintainers
- [ ] Upgrade Celery to the latest version

**Comment by jpowie01** [comment]
New version of Celery seems to be very stable! 💪
