### ISSUE TITLE
Check Minio (S3 Storage) as a replacement for current Cassandra or File System

### ISSUE THREAD

**Issue by jpowie01** [medtagger/MedTagger#607]
## Current Behavior

Currently we use Cassandra as a key-value storage for images. It seems to work quite well and performant. However, it uses too much resources and its Python driver seems too be quiet for some time. It's high time to consider a change and support S3 Storage.

Two years ago, there were not so many good storages that could be set up locally in Docker. The only S3 Storage that was reasonable to use was Amazon S3 in the cloud... Now, there are many more!

## Expected Behavior

Let's prepare a POC for Minio (https://github.com/minio/minio). Remove Cassandra support from MedTagger and replace it with S3 Storage backed by e.g. Minio or any other S3-compatible storage.

This will allow us to scale even better in the cloud!

## Tasks to do

- [ ] Prepare Docker environment with Minio
- [ ] Replace existing Cassandra code and migrate it to Minio
- [ ] Test it using existing functional and e2e tests
- [ ] Benchmark it and compare with existing architecture
