### ISSUE TITLE
Change the name of LabelElement to Annotation

### ISSUE THREAD

**Issue by jpowie01** [medtagger/MedTagger#630]
## Current Behavior

Label contains many "Label Elements". Sadly, the name does not reflect "business entity", so it would be cool to change this class' name sooner or later.

## Expected Behavior

I think that "Annotation" name fits better in the context of business relation to this entity. "Label Element" is fine but code and documentation is unreadable and requires additional "common" knowledge.

## Tasks to do

- [ ] Refactor backend code
- [ ] Refactor frontend code
- [ ] Make sure that tests pass
- [ ] Update documentation
